### PR TITLE
Readme

### PR DESCRIPTION
**Pull request by qwo**
issue https://github.com/c4hrva/hrt-bus-finder/issues/14

### CODE REVIEW

**Comment by bschoenfeld** [comment]
This is a good start, but needs to be squashed into one commit.

$ git rebase -i upstream/gh-pages

Change the start of every line (except the top one) from 'pick' to 's' (for squash).

**Comment by qwo** [comment]
ok thanks @bschoenfeld  for the feedback.

Will followup

**Comment by BretFisher** [comment]
why does it need to be one commit?  pull requests auto update as he commits to his repo/branch. Was Pull Request failing with merge conflict?

**Comment by bschoenfeld** [comment]
It doesn't NEED to be one commit, but it's good practice. Typically, you want to keep your master branch history clean and clear about changes that happened. So the history should have one commit saying that the README file was updated with basic info about the app. We really don't want commits like "Fixed a typo" on master when that was just an iterative step in the goal of this commit. It makes the history more difficult to read and use. And we really don't want that last merge commit because the parents and the resulting commit are all a part of his repo. Having that history copied over to our repo can be confusing. All that being said, @stanzheng didn't need to close this pull request. He could have rebased and forced a push. That's generally regarded as bad practice because you shouldn't change history that you have made public; but if you can be pretty sure that no one else has consumed that history and you won't cause anyone else problems by altering it, I think it's OK.

So that's pretty annoying, right? I'm being completely pedantic about this silly project's history. I'm stressing this because it really is good practice and one of the primary things I get out of CfA is professional development. I've read a bunch of opinions on git best practices and I really agree with the ones that stress maintaining a clean master history ([here's one from a technical lead a Twitter](https://sandofsky.com/blog/git-workflow.html)). I've also seen these types of requests on pull requests in much larger projects. I'll be glad to help anyone figure out how to clean up their history. I've only master it recently, but I love doing it. It's a really powerful tool.

**Comment by BretFisher** [comment]
Ben I'm 100% onboard with this. I like us all learning as we do. I think in
this case I was afraid we might have lost @stanzheng's commits because of a
utopian technical goal, but it sounds like a minor change in our PR
workflow and something that helps us all be awesomer. Now that we have
Brandon wanting to assist but not step on toes of WIP, Stanley are you able
to follow Ben's guidelines for getting your readme in place so others can
build off it?

**Comment by bschoenfeld** [comment]
Ha! This is Github! Nothing is ever lost!

**Comment by bmf** [comment]
Glad I checked this issue! I've written the basic README.md for this project, but now I'm not sure it was needed! ;) I'll be optimistic and issue the pull request and await y'all to tell me if you'll use it or not.

**Pull request closed without merging**
