### PR TITLE
I modified the color for the amount of time it will take for the bus …

### PR DESCRIPTION
**Pull request by BittenBagel**
…to arrive. With the additional classes of .forthcoming (green #84BA71), .advancing (yellow #E0CC47), and .approaching. (orange #E89F131). I also removed a period that was lingering on line 255, 256 above the .timeframe class.

I don't think messed anything up. So here it is!

### CODE REVIEW

**Comment by bschoenfeld** [comment]
You've got to add you node_modules folder to your .gitignore. You might need to manually delete it first, commit the deleted files, then squash your commit. We don't want to pull all these files into our code base, even in history.

**Comment by BittenBagel** [comment]
Ok, I'll go over it with Code4HR tomorrow. I need to head to work now. Thanks!

**Comment by wbprice** [comment]
I'll add node_modules to .gitignore tonight.  Thought it was already taken care of, sorry!

**Comment by bschoenfeld** [comment]
It was added a while ago. I'm not sure how @BittenBagel committed them, but we might need a git expert to help out :)

**Comment by wbprice** [comment]
I changed `node_modules/*` to `node_modules` in `.gitignore`.  Seems like a very minor difference, but the latter looks more common. @BittenBagel did you use the `--force` flag when adding files?

**Comment by wbprice** [comment]
@BittenBagel A solution is described here: https://gist.github.com/paulallies/0052fab554b14bbfa3ef
node_modules was added to the .gitignore a moment ago, and instead of pushing to master you'll be pushing to gh-pages.

**Comment by wbprice** [comment]
@BittenBagel pretty sure this was resolved in a different pull request, so closing this one for now.

**Pull request closed without merging**
