### PR TITLE
Refresh button

### PR DESCRIPTION
**Pull request by wbprice**
Added refresh button (with a lot of help from @bschoenfeld).  On click, stop information is refreshed and browser scrolls to top of screen.

### CODE REVIEW

**Comment by wbprice** [comment]
@bschoenfeld Did I do something seriously wrong with this and #106, or have you just been really busy?

**Comment by bschoenfeld** [comment]
I always assume that you have done something seriously wrong, but that
assumption continues to go unfounded! ;) Just kidding - been busy / taking
a cool down break from CfA coding. I'll get to it soon. I promise!

**Comment by bschoenfeld** [comment]
Doh! I merged #106, and now I can't merge this one. Can you rebase it or something?

**Comment by wbprice** [comment]
or something.

**Comment by bschoenfeld** [comment]
Use the Rebase, @wbprice. The Rebase is what gives a Githuber his power. It surrounds us and penetrates us. It binds the galaxy together.

**Pull request merged**
