### PR TITLE
fixed locator falling on newline by positioning locator and title absolutely.

### PR DESCRIPTION
**Pull request by wbprice**
Load speed, even for just the header and footer is pretty bad.  I'm going to be working on speeding everything up this Wednesday.

### CODE REVIEW

**Comment by bschoenfeld** [comment]
I'm going to teach you how to get rid of those ugly commits about CNAME. They have nothing to do with the pull request and we don't want them in our main repo's history!

First, make sure you have upstream set as a remote. Upstream should be the c4hrva repo

```
$git remote -v
origin  https://github.com/bschoenfeld/hrt-bus-finder.git (fetch)
origin  https://github.com/bschoenfeld/hrt-bus-finder.git (push)
upstream    https://github.com/c4hrva/hrt-bus-finder.git (fetch)
upstream    https://github.com/c4hrva/hrt-bus-finder.git (push)
```

Fetch upstream

```
$ git fetch upstream
```

Make sure you are on your gh-pages branch

```
$ git checkout gh-pages
Switched to branch 'gh-pages'
$ git status
# On branch gh-pages
nothing to commit (working directory clean)
```

Create a new branch

```
$ git checkout -b locator-position
Switched to a new branch 'locator-position'
```

Rebase!

```
$ git rebase -i upstream/gh-pages
```

At this point, you will be thrown into a text editor (mine is vim). You should see a number of commits. We want to squash all the commits into one. Leave the first line alone, but change 'pick' to 's' on every line after the first one. In vim, I type 'down arrow' to get to the next line, 'c', 'w', 's', 'Esc' - that is, change, word, to 's', exit insert mode. Repeat until I get through all the lines. Now save and exit (in vim - ':wq[Enter]'). 

Now you will get another text editor asking you to fix the commit message. It will automatically include all the squashed commit messages in this one commit. I usually delete all the lines and re-write the commit (in vim - 'dd' deletes a line, 'i' begins insert mode, 'Esc' to leave insert mode, ':wq[Enter]' to save and exit).

Finally push this branch and re-submit the pull request using this new branch instead your gh-pages branch.

**Comment by bschoenfeld** [comment]
It looks like you did the rebase correctly, but then you merged that branch into your gh-pages, so this pull request still has all those CNAME commits.

Your gh-pages branch should never have the CNAME file and the upstream always should, so you can never submit a proper pull request from that branch. All your pull-requests should come from feature branches that have been rebased to upstream/gh-pages.

**Comment by wbprice** [comment]
cool. new pull request is coming from the locator-position branch.

**Comment by bschoenfeld** [comment]
Reopened as #33

**Pull request closed without merging**
