### PR TITLE
Fixed -- Rethink Disclaimer #115

### PR DESCRIPTION
**Pull request by waphelps**
I do not consider myself a programmer; but, this was preventing use on
some commonly carried items.  I used a KISS method to display/dismiss
the disclaimer that should work on most devices.

### CODE REVIEW

**Comment by qwo** [comment]
hi @waphelps,
thanks for the contribution, I think this is a great idea and style that we should consider. 

I'll wait for @wbprice and @bschoenfeld to chime in but I think this is a great feature. Using a local-cookie to remind people every week in an inline reminder is something I can get behind, and disappearing after 20 seconds

https://github.com/waphelps/hrt-bus-finder/blob/gh-pages/index.html#L213
screenshot 2014-07-28 20 45 59

I pulled it down and checked it and it looks good to me.

**Comment by wbprice** [comment]
IIRC, the current behavior is to hide the disclaimer for the given device forever after viewed once. I don't think it's necessary to bring it back every week.  Also, no profanity. Think of the children!

**Comment by waphelps** [comment]
The thought behind the expiration was to gently enforce viewing while
allowing for the possibility of a new message without having to explicitly
delete the cookie -- maybe even presenting a Message Of The Week.  And,
what profanity; I Unnecessarily Censored™ the statement to allow the reader
to substitute their own thoughts -- I was thinking about kittens and
rainbows. [?]

**Comment by qwo** [comment]
> I was thinking about kittens and rainbows. [?]

I approve :), however I'm not too hot on the last one, and would like to suggest friendlier language. 

We use a cookie so ~~that you will not be @#$$*& frustrated by seeing~~ this message **won't** be seen more than once a week.

I would be happy to make the suggested change and pull this in ASAP

**Comment by waphelps** [comment]
That's fine.  The real reasons for that sentence are: first, to let people know that they need to have cookies enabled to keep the message from appearing every time; and, second to provide a warning for those outside the US who accidentally stumble upon this very local site.

**Comment by BretFisher** [comment]
I think we would accept a pull request that only fixes the modal presentation issue, and leaves alone the current disclaimer text and frequency. Thanks for the help @waphelps and we welcome that revision to your pull request. Sorry for the delay.

**Pull request closed without merging**
