### PR TITLE
lockview

### PR DESCRIPTION
**Pull request by qwo**
reference this issue

https://github.com/c4hrva/hrt-bus-finder/issues/51

### CODE REVIEW

**Comment by bschoenfeld** [comment]
Can you move the map on desktop?

**Comment by qwo** [comment]
you can mimic the gestures of the phone

zooming: scrolling in using mouse wheel  or double clicking 
zooming out: scrolling out using mouse wheel 

do not know the equivalent of a (zoom out pinch gesture) on browsers 

but yes it works on browsers 

**edit : On browser there are map controls enabled, so they can use those to explore the map

**Comment by bschoenfeld** [comment]
I agree this is a good change for the stop list view, but I don't like it for the route view (and the upcoming stop search view). Can you implement this in the router? When we route to home or stop list view, call a method on the map view that sets draggable to false. For all other routes, set it to true.

**Comment by qwo** [comment]
Ill look into it

**Comment by bschoenfeld** [comment]
Also, make sure you rebase all your commits onto upstream/gh-pages so they can be merged.

$ git fetch upstream
$ git rebase upstream/gh-pages
$ git push origin branch-name --force

Thanks!

**Pull request closed without merging**
