### PR TITLE
Use the snow route mode for a sunset message

### PR DESCRIPTION
**Pull request by bschoenfeld**
Took a shot at the sunset message. Still need to test it, make sure it looks OK, etc. Open to feedback on the message.

### CODE REVIEW

**Comment by qwo** [comment]
The end of an era. Cake must be had

**Comment by BretFisher** [comment]
Can we also remove the popup warning?

**Comment by bschoenfeld** [comment]
@BretFisher The app has been completely disabled except for the goodbye message. It's rolled out. Check it now. I think the warning you are referring to is gone.

**Comment by BretFisher** [comment]
Just tested incognito and still get disclaimer

**Comment by bschoenfeld** [comment]
Ahhh yes. Good call. It's gone.

24881999d0fe412f02632a07fd920bcf19cbd540

**Pull request merged**
